### ISSUE TITLE
AutomaticComponentToolkit Architecture

### ISSUE THREAD

**Issue by cilynx** [koendv/openscad-raspberrypi#1]
Did you have to build a new `act.linux` from `AutomaticComponentToolkit`?  When I clone `lib3mf`, the `act.linux` that comes along with is an ia64 binary that won't run on the Pi.  Rebuilding `AutomaticComponentToolkit` from source to get an ARM binary made things work for me.

**Comment by koendv** [comment]
OK. Looks like an omission on my part. I've added building AutomaticComponentToolkit to the README. Thanks.
