### ISSUE TITLE
RPi4 Segmentation fault

### ISSUE THREAD

**Issue by erichstuder** [koendv/openscad-raspberrypi#5]
OpenSCAD-2021.03.26-armhf.AppImage worked fine until about a few days ago.
I have a Raspberry Pi 4 with 4GB RAM which is up to date.

Reproduction:
- Download: https://github.com/koendv/openscad-raspberrypi/releases/download/v1.6/OpenSCAD-2021.03.26-armhf.AppImage
- Make executable
- Execute: ./OpenSCAD-2021.03.26-armhf.AppImage
- Result Message: Segementation fault

**Comment by koendv** [comment]
On Thu, 09 Sep 2021 07:08:15 -0700
erichstuder ***@***.***> wrote:

> OpenSCAD-2021.03.26-armhf.AppImage worked fine until about a few days
> ago. I have a Raspberry Pi 4 with 4GB RAM which is up to date.
> 
> Reproduction:
> - Download:
> https://github.com/koendv/openscad-raspberrypi/releases/download/v1.6/OpenSCAD-2021.03.26-armhf.AppImage
> - Make executable
> - Execute: ./OpenSCAD-2021.03.26-armhf.AppImage
> - Result Message: Segementation fault
> 
> 

OK. I'll recompile.

koen

**Comment by koendv** [comment]
Could you check OpenSCAD-2021.09.13-armhf.AppImage in releases?

**Comment by erichstuder** [comment]
> Could you check OpenSCAD-2021.09.13-armhf.AppImage in releases?

The Segmentation fault is gone.
Thank you very much!
